# fly.toml app configuration file generated for computelematic on 2024-09-28T20:23:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'computelematic'
primary_region = 'bog'

[build]

[http_service]
  internal_port = 1111
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
