server:
  port: 1111
  servlet:
    context-path: "/"
spring:
  application:
    name: "reactive-application-computelematic"
  main:
    web-application-type: "reactive"
  profiles:
    active: "${SPRING_PROFILE_ACTIVE:dev}"
