server:
  port: 1111
  servlet:
    context-path: "/"
spring:
  application:
    name: "reactive-application-computelematic"
  main:
    web-application-type: "reactive"
  config:
    activate:
      on-profile: "${SPRING_PROFILE_ACTIVE:dev}"