server:
  port: 1111
  servlet:
    context-path: "/"
spring:
  application:
    name: "reactive-application-computelematic"
  main:
    web-application-type: "reactive"
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: "${SPRING_PROFILE_ACTIVE:dev}"
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8
database:
  host: localhost
  port: 5432
  name: computelematic_db
  username: cmt_admin_user
  password: Cmt.2024.db