server:
  port: 1111
  servlet:
    context-path: "/"
spring:
  application:
    name: "reactive-application-computelematic"
  main:
    web-application-type: "reactive"
    allow-bean-definition-overriding: true
  config:
    activate:
      on-profile: "${SPRING_PROFILE_ACTIVE:dev}"
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    cache: false
    encoding: UTF-8
database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
